[package]
name = "merkle-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = { version = "^0.10.4" }
sha3 = { version = "^0.10.5" }

hex = { version = "^0.4" }
